/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.clinica.gui;

import javax.swing.JDialog;

/**
 *
 * @author jacob
 */
public class AntecedentesFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Antecedentes
     */
    public AntecedentesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHereditario = new javax.swing.JButton();
        btnPatologico = new javax.swing.JButton();
        btnNoPatologico = new javax.swing.JButton();

        setTitle("Antecedentes");

        btnHereditario.setText("Hereditario");
        btnHereditario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHereditarioActionPerformed(evt);
            }
        });

        btnPatologico.setText("Patológico");
        btnPatologico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatologicoActionPerformed(evt);
            }
        });

        btnNoPatologico.setText("No Patológico");
        btnNoPatologico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoPatologicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnHereditario)
                .addGap(18, 18, 18)
                .addComponent(btnPatologico)
                .addGap(18, 18, 18)
                .addComponent(btnNoPatologico)
                .addContainerGap(816, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHereditario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPatologico, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNoPatologico, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(534, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHereditarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHereditarioActionPerformed
        HereditarioFrame hereditario = new HereditarioFrame(null, true);
        hereditario.setLocationRelativeTo(null);
        hereditario.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        hereditario.setLocation(600, 150);
        hereditario.setAlwaysOnTop(true);
        hereditario.setVisible(true);
    }//GEN-LAST:event_btnHereditarioActionPerformed

    private void btnPatologicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatologicoActionPerformed
        PatologicoFrame patologico = new PatologicoFrame(null, true);
        patologico.setLocationRelativeTo(null);
        patologico.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        patologico.setLocation(600, 150);
        patologico.setAlwaysOnTop(true);
        patologico.setVisible(true);
    }//GEN-LAST:event_btnPatologicoActionPerformed

    private void btnNoPatologicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoPatologicoActionPerformed
        NoPatologicoFrame noPatologico = new NoPatologicoFrame(null, true);
        noPatologico.setLocationRelativeTo(null);
        noPatologico.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        noPatologico.setLocation(600, 150);
        noPatologico.setAlwaysOnTop(true);
        noPatologico.setVisible(true);
    }//GEN-LAST:event_btnNoPatologicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHereditario;
    private javax.swing.JButton btnNoPatologico;
    private javax.swing.JButton btnPatologico;
    // End of variables declaration//GEN-END:variables
}
